# Generated by Django 3.0 on 2019-12-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_auto_20190719_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='is_relation',
            field=models.BooleanField(default=True),
        ),
    ]
