# Generated by Django 3.0 on 2020-01-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_relation_is_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='User Image'),
        ),
    ]
