# Generated by Django 3.0.3 on 2020-02-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0005_relation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
