# Generated by Django 2.2.3 on 2019-07-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datemodel',
            options={'verbose_name': 'Date Model', 'verbose_name_plural': 'Date Models'},
        ),
        migrations.AlterModelOptions(
            name='datetimemodel',
            options={'verbose_name': 'Date Time Model', 'verbose_name_plural': 'Date Time Models'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'Time Model', 'verbose_name_plural': 'Time Models'},
        ),
    ]
