# Generated by Django 3.0 on 2019-12-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0002_auto_20190719_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datemodel',
            options={'ordering': ('my_order',), 'verbose_name': 'Date Model', 'verbose_name_plural': 'Date Models'},
        ),
        migrations.AddField(
            model_name='datemodel',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
