# Generated by Django 3.0 on 2019-12-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0003_auto_20191210_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=255, verbose_name='Period1')),
            ],
            options={
                'verbose_name': 'Period1',
                'verbose_name_plural': 'Periods1',
            },
        ),
        migrations.CreateModel(
            name='Period2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=255, verbose_name='Period2')),
            ],
            options={
                'verbose_name': 'Period2',
                'verbose_name_plural': 'Periods2',
            },
        ),
        migrations.CreateModel(
            name='Period3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=255, verbose_name='Period3')),
            ],
            options={
                'verbose_name': 'Period3',
                'verbose_name_plural': 'Periods3',
            },
        ),
    ]
