# Generated by Django 2.2.2 on 2019-06-24 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_country_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 24, 9, 50, 45, 813267)),
            preserve_default=False,
        ),
    ]
