# Generated by Django 2.2.2 on 2019-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_person_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
