# Generated by Django 2.2.2 on 2019-07-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0012_auto_20190710_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('countries.person',),
        ),
    ]
