# Generated by Django 2.2.3 on 2019-07-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0013_proxyperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyperson',
            options={'verbose_name': 'Proxy Person', 'verbose_name_plural': 'Proxy Persons'},
        ),
    ]
