# Generated by Django 2.2.3 on 2019-07-19 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0014_auto_20190719_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='created',
            field=models.DateField(verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_safe',
            field=models.BooleanField(default=True, verbose_name='Is safe'),
        ),
        migrations.AlterField(
            model_name='country',
            name='modified',
            field=models.DateTimeField(verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(null=True, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='country',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
