# Generated by Django 3.0 on 2020-01-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0017_country1_country2_country3_country4_country5_country6'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='time',
            field=models.TimeField(null=True, verbose_name='Birth Time'),
        ),
    ]
