# Generated by Django 3.0.7 on 2020-07-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0019_auto_20200127_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='Name', max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_es',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_uk',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_zh_hans',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
    ]
