# Generated by Django 2.2 on 2019-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture')),
                ('population', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('r', 'Republic'), ('cm', 'Constitutional monarchy'), ('am', 'Absolute monarchy'), ('n', 'N/A')], max_length=2, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'verbose_name': 'County',
                'ordering': ('name',),
                'db_table': 'country',
            },
        ),
    ]
