# Generated by Django 2.2.2 on 2019-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_createsuperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_safe',
            field=models.BooleanField(default=True),
        ),
    ]
