# Generated by Django 2.2.2 on 2019-06-24 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_country_is_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='created',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
