# Generated by Django 2.2.3 on 2019-07-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(null=True, verbose_name='Url'),
        ),
    ]
