# Generated by Django 3.0 on 2019-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
