# Generated by Django 3.0 on 2019-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('choice1', 'Choice1'), ('choice2', 'Choice2'), ('choice3', 'Choice3'), ('choice4', 'Choice4'), ('choice5', 'Choice5'), ('choice6', 'Choice6'), ('choice7', 'Choice7'), ('choice8', 'Choice8'), ('choice9', 'Choice9'), ('choice10', 'Choice10'), ('choice11', 'Choice11')], max_length=64, null=True, verbose_name='Type'),
        ),
    ]
